- CHANGELOG.md
- renderers/BaseRenderer.php
| New feature?  | yes
| Fixed issues  | -
See https://github.com/yiisoft/yii2/issues/12055#issuecomment-236843198
> Add support for `int` and `bool` types

- README.md
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Fix missed letter

- apidoc
Fixes #152.
| Fixed issues  | #152
> Set alias @bower and @npm to @vendor/{bower-asset,@npm-asset}

- CHANGELOG.md
- composer.json
> Upgraded highlight.js dependency

- CHANGELOG.md
- helpers/ApiMarkdown.php
- tests/commands/GuideControllerTest.php
- tests/data/guide/TOC.md
| New feature?  |no
| Breaks BC?    |no
| Fixed issues  | #176
> Make sure only one TOC is rendered in ApiMarkdown

- CHANGELOG.md
- models/TypeDoc.php
| New feature?  | yes
| Fixed issues  | #7, #132
> Fix #7, fix #132: Add support for `@property` and `@method`

- CHANGELOG.md
- templates/bootstrap/assets/HighlightBundle.php
The current path with `_`, but actually with `-`.
> Fix css path

- CHANGELOG.md
- models/BaseDoc.php
> Extended detection of `@inheritdoc`  in `BaseDoc`

- CHANGELOG.md
- templates/html/views/type.php
> Fixed "All Classes" broken link

- helpers/MarkdownHighlightTrait.php
| Fixed issues  | 
An addition to the latest merge. Sorry, forgot about this.
> Fixed strpos usage

- models/TypeDoc.php
…ties
| Fixed issues  | 
A fix to the bug introduced in #225.
> Fixed regression after adding of skipping internal methods and properties

- CHANGELOG.md
- helpers/MarkdownHighlightTrait.php
- models/Context.php
- models/InterfaceDoc.php
| Fixed issues  | #168 
---
**TODO list:**
> Fix handling of inheritance (classes)

- README.md
> Added output of help commands to the docs

- README.md
> Added note about README.md presence during generating guide to the docs

- models/Context.php
> Fixed copy paste error in message about inherited property

- CHANGELOG.md
- models/TypeDoc.php
> Do not show a "virtual" / "magic" methods's full description if it matches short description

- CHANGELOG.md
- models/BaseDoc.php
- templates/bootstrap/assets/css/style.css
- templates/html/views/changelog.php
- templates/html/views/eventDetails.php
- templates/html/views/methodDetails.php
- templates/html/views/methodSourceCode.php
- templates/html/views/propertyDetails.php
- templates/html/views/type.php
> Added support for multiple "since" tags

- .github/ISSUE_TEMPLATE.md
> Fixed typo in ISSUE_TEMPLATE.md

- CHANGELOG.md
- templates/html/views/methodDetails.php
- templates/html/views/methodSourceCode.php
> Do not show a method's source code when it's empty

- CHANGELOG.md
- README.md
- commands/ApiController.php
- components/BaseController.php
- helpers/ApiMarkdown.php
- renderers/BaseRenderer.php
> Added support to relative links within a repository

- composer.json
> Add intl as suggested extension to composer.json

- CHANGELOG.md
- templates/html/ApiRenderer.php
- templates/html/views/type.php
| Fixed issues  | #36
Also did minor cleanup of unused parameters.
> Allow to customize "All classes" url and "Available since version" label for type in HTML API

- helpers/PrettyPrinter.php
- models/ConstDoc.php
- models/Context.php
- models/PropertyDoc.php
| Fixed issues  | #263 (partially)
Based on this suggestion https://github.com/phpDocumentor/Reflection/issues/224#issuecomment-982986432.
> Inject custom pretty printer through strategies

- templates/html/views/methodSourceCode.php
| Fixed issues  | A follow up for #147.
> Prevent scroll when opening a method's source code

- helpers/ApiMarkdownTrait.php
| Fixed issues  | A follow up to #161 / #255.
> Fix encoding in API link text

- helpers/ApiMarkdownLaTeX.php
| Fixed issues  | A follow up to #274
> Fix case in check for inline code

- templates/bootstrap/views/index.php
| Fixed issues  | Related - #289
> Additions to 289 PR

- templates/bootstrap/views/index.php
| Fixed issues  | Related - #289
> Revert `ksort` for classes at index page

- CHANGELOG.md
- models/Context.php
> Improve handling of trait inheritance - precedence, prevent methods' and properties' duplication

- models/Context.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-apidoc/issues/302
> update models folder links

- README.md
- apidoc
- apidoc.bat
- composer.json
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-apidoc/issues/308
> update root folder links
