templates/bootstrap/assets/css/style.css

Limit content image width to 100%

---

renderers/BaseRenderer.php

| Tests pass?   | not tested
| Fixed issues  |  #9922, https://github.com/yiisoft/yii2/issues/9922
When an url in the guide is refering to an url out of the guide project itself, avoid parsing url to keep it working (used in side nav bar).
Example:
[Advanced Project Template]\(https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/README.md)

Fix broken links with external urls

---

CHANGELOG.md
commands/ApiController.php
models/BaseDoc.php
models/Context.php
models/PropertyDoc.php

| New feature?  | yes
| Fixed issues  | -
Before:
After:
Most of these warnings is about missing phpdoc in AssetsBundles. I think it is worth to separate such errors  (which will be just ignored on rendered page) from errors which will result broken links and probably means some typo.

Separate warnings and errors occurred on processing files

---

CHANGELOG.md
renderers/BaseRenderer.php
tests/commands/ApiControllerTest.php

| Fixed issues  | -
www.php.net permanently redirects to HTTPS.
```bash
$ curl -vvv http://www.php.net
* Rebuilt URL to: http://www.php.net/
*   Trying 2a02:cb40:200::1ad...
* TCP_NODELAY set
* Connected to www.php.net (2a02:cb40:200::1ad) port 80 (#0)
> GET / HTTP/1.1
> Host: www.php.net
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: myracloud
< Date: Fri, 03 Jan 2020 08:02:10 GMT
< Content-Type: text/html
< Content-Length: 177
< Connection: keep-alive
< Location: https://www.php.net/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center> …
```

www.php.net links with HTTPS

---

CHANGELOG.md
models/BaseDoc.php
models/Context.php

Also added `BaseDoc::getPackageName()` to help determine the package name of the method/property based on its sourceFile. If `getPackageName()` differs between the current method/property and its parent class it's inheriting from, then @since won't be copied.
| New feature?  | yes
| Fixed issues  | #137

Propagate @since to inherited methods/properties

---

CHANGELOG.md
models/Context.php

Fixed invalid attempt to scan parent class of interface with `@inheritdoc` tag on a method.
| Tests pass?   | yes/no
| Fixed issues  | #210

Fixed invalid attempt to scan parent class of interface

---

CHANGELOG.md
helpers/MarkdownHighlightTrait.php

| Fixed issues  | #34 
Seems like a solid workaround with minimal efforts / rewriting of code. Also it doesn't require manual replacing in the whole guide. Based on [this comment](https://github.com/scrivo/highlight.php/issues/74#issuecomment-624263627). Maybe there are more problematic cases, but from what I see it works fine.
Also here are visual diffs for blocks mentioned in the original issue.
Block 1, before:
Block 1, after:
Block 2, before:
Block 2, after:

Improved highlighting of PHP templates

---

CHANGELOG.md
helpers/MarkdownHighlightTrait.php
models/BaseDoc.php
models/MethodDoc.php
templates/html/ApiRenderer.php
templates/html/views/methodDetails.php
templates/html/views/type.php
tests/data/api/animal/Cat.php
tests/data/api/animal/Dog.php

Added feature of viewing method source code without external links

---

models/BaseDoc.php
tests/models/BaseDocTest.php

| Fixed issues  | 
A fix to the bug introduced in #228.

BaseDoc::extractFirstSentence() must consider previous text

---

CHANGELOG.md
models/TypeDoc.php

Fixed a bug when a "virtual" / "magic" property's full description was displayed instead of preview in properties list

---

CHANGELOG.md
README.md
helpers/ApiMarkdownLaTeX.php
templates/pdf/GuideRenderer.php
templates/pdf/Makefile
templates/pdf/main.tex

| Fixed issues  | #134, #170
Some brief visual examples of changes.
Before (PHP):
After (PHP):
Before (JS):
After (JS):

Swap listings package with minted for better code highlighting in PDF guide

---

CHANGELOG.md
helpers/ApiMarkdownLaTeX.php
helpers/ApiMarkdownTrait.php

| Fixed issues  | #161
Now it's possible to write:
<pre>[[ApplicationTrait::getEntries()|`Craft::$app->entries`]]</pre>
<pre>[[ApplicationTrait::getEntries()|*Craft::$app->entries*]]</pre>
<pre>[[ApplicationTrait::getEntries()|**Craft::$app->entries**]]`</pre>
etc.
PDF version is left as is (all HTML tags are stripped). Not sure if we need to change this behavior. Can be discussed.

Render API link text

---

README.md
commands/ApiController.php
components/BaseController.php
helpers/ApiMarkdown.php
renderers/ApiRenderer.php
renderers/BaseRenderer.php

| Fixed issues  | Fixes after retest of #256 (logic + regression)

Use repo url only in api, fixed regression of processing absolute links containing word "guide"

---

CHANGELOG.md
models/Context.php
models/TypeDoc.php
renderers/BaseRenderer.php
templates/bootstrap/layouts/api.php
templates/html/views/constSummary.php
templates/html/views/eventDetails.php
templates/html/views/eventSummary.php
templates/html/views/methodDetails.php
templates/html/views/methodSummary.php
templates/html/views/propertyDetails.php
templates/html/views/propertySummary.php
tests/commands/ApiControllerTest.php

| Fixed issues  | #124
Still have doubts if it's worth it but related changes could be useful in the future. Anyways, here are things done:
- Inherited and magic methods' details are now included to a current page:
- All summary links lead to the same page now.
- For inherited methods the link for external page moved to details.
- Adapted toggle for using with details and added it for hiding inherited methods.
- The same applies to properties and events (for consistency).
- Other features like viewing method's source code without leaving current page are supported.
- Added missing full name for magic properties and methods (defined via PHPDoc tags `@property` / `@method` and getters / …

Resolve static return type

---

composer.json

- Use the latest stable version (new release - https://github.com/phpDocumentor/Reflection/releases/tag/5.1.0).
- Increase minimum stability to "stable".
- Remove 2.1 branch alias (because of upcoming 3.0 release).

Update "phpdocumentor/reflection" version

---

helpers/ApiMarkdownLaTeX.php

| Fixed issues  |  
Not rendered anyway, but causes minted to crash during guide generation (if followed by another inline code block, Japanese language is affected).

Remove inline code in headlines in PDF guide

---

CHANGELOG.md
models/Context.php

| Fixed issues  | https://github.com/yiisoft-contrib/yiiframework.com/issues/986

Do not cache Context::getReflectionProject() at instance level because it can cause apidoc cache to contain not actual data

---

CHANGELOG.md
templates/bootstrap/GuideRenderer.php
templates/html/GuideRenderer.php

| Fixed issues  | https://github.com/yiisoft/yii2/issues/19248

Fix encoding in non English guides

---

CHANGELOG.md
models/BaseDoc.php
tests/models/BaseDocTest.php

source comment:
~~~markdown
a URI [RFC3986](https://tools.ietf.org/html/rfc3986) or
URI template [RFC6570](https://tools.ietf.org/html/rfc6570). This property is required.
~~~
before fix `BaseDoc::extractFirstSentence()` return:
`a URI [RFC3986](https://tools.`
after:
`a URI [RFC3986](https://tools.ietf.org/html/rfc3986) or URI template [RFC6570](https://tools.ietf.org/html/rfc6570).`
is dirty fix, but covering main cases
| Fixed issues  | 
---
Minor additions for historical purposes by @arogachev.
Newline (only affects HTML code, not visual output):
https://github.com/yiisoft/yii2/blob/2874e070f3ad88c727b1335ba4f4515855bf5f64/framework/base/Controller.php#L48-L52
- …

Convert newlines to spaces and consider the first sentence ended only if the dot is followed by a space in `BaseDoc::extractFirstSentence()`

---

templates/bootstrap/views/index.php

Fix imports and semantics in HTML in `templates/bootstrap/views/index.php`

---

CHANGELOG.md
commands/ApiController.php

| Fixed issues  | -
The same error or warning might be logged multiple times. This PR deduplicate them before writing them to their respective files.

Deduplicate logged errors and warnings

---

README.md

Fix composer to installable version. Update documentation

---

templates/bootstrap/SideNavWidget.php
templates/bootstrap/assets/css/style.css
templates/pdf/main.tex
templates/pdf/title.tex

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-apidoc/issues/304

update templates folder links

---

tests/commands/ApiControllerTest.php
tests/commands/GuideControllerTest.php
tests/data/api/animal/Animal.php
tests/data/api/animal/Cat.php
tests/data/api/animal/Dog.php
tests/models/BaseDocTest.php
tests/support/controllers/ApiControllerMock.php
tests/support/controllers/GuideControllerMock.php
tests/support/controllers/StdOutBufferControllerTrait.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-apidoc/issues/306

update tests folder links
